language: csharp
os: linux
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono:
  - latest
dotnet: 1.0.1
script:
  - ./build.sh --target "Travis" --platform "Any CPU" --configuration "Release"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/17f3a182e1e1bc5e7bcd
    on_success: change
    on_failure: always
    on_start: never
