language: csharp
os:
  - linux
  - osx
mono:
  - latest
script:
  - ./build.sh --target "Travis" --platform "Any CPU" --configuration "Release"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/17f3a182e1e1bc5e7bcd
    on_success: change
    on_failure: always
    on_start: never
