language: csharp
os:
  - linux
  - osx
mono:
  - latest
script:
  - sudo chmod +x build.sh
  - ./build.sh --target "Travis" --platform "Any CPU" --configuration "Release"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c56f9b5ff1c558c0db90
    on_success: change
    on_failure: always
    on_start: never
cache:
  directories:
    - packages
    - tools
