image: Visual Studio 2017
platform:
- Any CPU
configuration:
- Release
environment:
  NUGET_API_KEY:
    secure: iSkm19DNdKOLxxCvHiaKikWXy25ZMwGBKpv+EgEprliGl0qX5HtKohLmwJsLnx5O
  NUGET_API_URL: https://www.nuget.org/api/v2/package
  MYGET_API_KEY:
    secure: xhYvrWYPHdNI+mQD+f4Zu3baL7fqW+nO/hYXJdN070Lej8wpa6gfrLi1NGtnQlAs
  MYGET_API_URL: https://www.myget.org/F/xamlbehaviors-nightly/api/v2/package
install:
  - if not exist dotnet-1.0.1.exe appveyor DownloadFile https://go.microsoft.com/fwlink/?linkid=843448 -FileName "dotnet-1.0.1.exe"
  - if not exist gtk-sharp-2.12.26.msi appveyor DownloadFile http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.26.msi
  - msiexec /i gtk-sharp-2.12.26.msi /qn /norestart
  - cmd: call dotnet-1.0.1.exe /quiet
  - cmd: set PATH=%programfiles(x86)%\GtkSharp\2.12\bin\;%PATH%
before_build:
- cmd: git submodule update --init
build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Platform "$env:platform" -Configuration "$env:configuration"
test: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/0e398f1cf5a16e63bff3
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
artifacts:
  - path: artifacts\test-results\*.xml
  - path: artifacts\nuget\*.nupkg
cache:
  - gtk-sharp-2.12.26.msi
  - dotnet-1.0.1.exe
