version: 2
jobs:
  build:
    working_directory: ~/AvaloniaBehaviors
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore src/Avalonia.Xaml.Interactivity
      - run: dotnet build src/Avalonia.Xaml.Interactivity/Avalonia.Xaml.Interactivity.csproj -c Release -f netstandard2.0
      - run: dotnet restore src/Avalonia.Xaml.Interactions
      - run: dotnet build src/Avalonia.Xaml.Interactions/Avalonia.Xaml.Interactions.csproj -c Release -f netstandard2.0
      - run: dotnet restore src/Avalonia.Xaml.Interactions.Custom
      - run: dotnet build src/Avalonia.Xaml.Interactions.Custom/Avalonia.Xaml.Interactions.Custom.csproj -c Release -f netstandard2.0
      - run: dotnet restore tests/Avalonia.Xaml.Interactivity.UnitTests
      - run: dotnet test tests/Avalonia.Xaml.Interactivity.UnitTests/Avalonia.Xaml.Interactivity.UnitTests.csproj -c Release -f netcoreapp2.0
      - run: dotnet restore tests/Avalonia.Xaml.Interactions.UnitTests
      - run: dotnet test tests/Avalonia.Xaml.Interactions.UnitTests/Avalonia.Xaml.Interactions.UnitTests.csproj -c Release -f netcoreapp2.0
      - run: dotnet restore tests/Avalonia.Xaml.Interactions.Custom.UnitTests
      - run: dotnet test tests/Avalonia.Xaml.Interactions.Custom.UnitTests/Avalonia.Xaml.Interactions.Custom.UnitTests.csproj -c Release -f netcoreapp2.0
      - run: dotnet restore samples/BehaviorsTestApplication.NetCore
      - run: dotnet build samples/BehaviorsTestApplication.NetCore/BehaviorsTestApplication.NetCore.csproj
    notify:
      webhooks:
        - url: https://webhooks.gitter.im/e/8b396be7e49e711c841c
